name: Integration Tests

on:
  push:
    branches: [ karolh2000/git_actions_experiments ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    env:
      RUSTC_WRAPPER: /home/runner/.cargo/bin/sccache
      CARGO_INCREMENTAL: 0
    steps:
      - uses: actions/checkout@v3

      # Clone the repo with submodules (bats)
      - name: Clone the repo with submodules (bats)
        run: |
          git clone --recurse-submodules -b  karolh200/integration-tests  https://github.com/karolh2000/pyrsia-integration-tests.git

      - name: Execute Test Cases
        run: |
          ./pyrsia-integration-tests/bats/run_tests.sh
